#[doc = "Register `CONTROL` reader"]
pub type R = crate::R<ControlSpec>;
#[doc = "Register `CONTROL` writer"]
pub type W = crate::W<ControlSpec>;
#[doc = "Field `abort` reader - Write `1` to this field to both initiate and acknowledge an abort. Empties both FIFOs, asserts `aborting`, and prevents an interrupt from being generated by an incoming abort request. New reads & writes are ignored until `aborted` is asserted from the peer."]
pub type AbortR = crate::BitReader;
#[doc = "Field `abort` writer - Write `1` to this field to both initiate and acknowledge an abort. Empties both FIFOs, asserts `aborting`, and prevents an interrupt from being generated by an incoming abort request. New reads & writes are ignored until `aborted` is asserted from the peer."]
pub type AbortW<'a, REG> = crate::BitWriter<'a, REG>;
impl R {
    #[doc = "Bit 0 - Write `1` to this field to both initiate and acknowledge an abort. Empties both FIFOs, asserts `aborting`, and prevents an interrupt from being generated by an incoming abort request. New reads & writes are ignored until `aborted` is asserted from the peer."]
    #[inline(always)]
    pub fn abort(&self) -> AbortR {
        AbortR::new((self.bits & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - Write `1` to this field to both initiate and acknowledge an abort. Empties both FIFOs, asserts `aborting`, and prevents an interrupt from being generated by an incoming abort request. New reads & writes are ignored until `aborted` is asserted from the peer."]
    #[inline(always)]
    pub fn abort(&mut self) -> AbortW<'_, ControlSpec> {
        AbortW::new(self, 0)
    }
}
#[doc = "\n\nYou can [`read`](crate::Reg::read) this register and get [`control::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`control::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct ControlSpec;
impl crate::RegisterSpec for ControlSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`control::R`](R) reader structure"]
impl crate::Readable for ControlSpec {}
#[doc = "`write(|w| ..)` method takes [`control::W`](W) writer structure"]
impl crate::Writable for ControlSpec {
    type Safety = crate::Unsafe;
}
#[doc = "`reset()` method sets CONTROL to value 0"]
impl crate::Resettable for ControlSpec {}
