#![doc = "Peripheral access API for SOC microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[doc = r" Interrupt numbers, priority levels, and HART IDs."]
pub mod interrupt;
#[doc = "PL230 DMA Controller Core"]
pub type Pl230 = crate::Periph<pl230::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Pl230 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pl230").finish()
    }
}
#[doc = "PL230 DMA Controller Core"]
pub mod pl230;
#[doc = "ALU"]
pub type Alu = crate::Periph<alu::RegisterBlock, 0x4002_f000>;
impl core::fmt::Debug for Alu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Alu").finish()
    }
}
#[doc = "ALU"]
pub mod alu;
#[doc = "AES"]
pub type Aes = crate::Periph<aes::RegisterBlock, 0x4002_d000>;
impl core::fmt::Debug for Aes {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aes").finish()
    }
}
#[doc = "AES"]
pub mod aes;
#[doc = "COMBOHASH"]
pub type Combohash = crate::Periph<combohash::RegisterBlock, 0x4002_b000>;
impl core::fmt::Debug for Combohash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Combohash").finish()
    }
}
#[doc = "COMBOHASH"]
pub mod combohash;
#[doc = "PKE"]
pub type Pke = crate::Periph<pke::RegisterBlock, 0x4002_c000>;
impl core::fmt::Debug for Pke {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pke").finish()
    }
}
#[doc = "PKE"]
pub mod pke;
#[doc = "TRNG"]
pub type Trng = crate::Periph<trng::RegisterBlock, 0x4002_e000>;
impl core::fmt::Debug for Trng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Trng").finish()
    }
}
#[doc = "TRNG"]
pub mod trng;
#[doc = "SCEDMA"]
pub type Scedma = crate::Periph<scedma::RegisterBlock, 0x4002_9000>;
impl core::fmt::Debug for Scedma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Scedma").finish()
    }
}
#[doc = "SCEDMA"]
pub mod scedma;
#[doc = "SCE_GLBSFR"]
pub type SceGlbsfr = crate::Periph<sce_glbsfr::RegisterBlock, 0x4002_8000>;
impl core::fmt::Debug for SceGlbsfr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SceGlbsfr").finish()
    }
}
#[doc = "SCE_GLBSFR"]
pub mod sce_glbsfr;
#[doc = "DUART"]
pub type Duart = crate::Periph<duart::RegisterBlock, 0x4004_2000>;
impl core::fmt::Debug for Duart {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Duart").finish()
    }
}
#[doc = "DUART"]
pub mod duart;
#[doc = "RBIST_WRP"]
pub type RbistWrp = crate::Periph<rbist_wrp::RegisterBlock, 0x4004_5000>;
impl core::fmt::Debug for RbistWrp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RbistWrp").finish()
    }
}
#[doc = "RBIST_WRP"]
pub mod rbist_wrp;
#[doc = "EVC"]
pub type Evc = crate::Periph<evc::RegisterBlock, 0x4004_4000>;
impl core::fmt::Debug for Evc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Evc").finish()
    }
}
#[doc = "EVC"]
pub mod evc;
#[doc = "SYSCTRL"]
pub type Sysctrl = crate::Periph<sysctrl::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for Sysctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sysctrl").finish()
    }
}
#[doc = "SYSCTRL"]
pub mod sysctrl;
#[doc = "BIO_BDMA"]
pub type BioBdma = crate::Periph<bio_bdma::RegisterBlock, 0x5012_4000>;
impl core::fmt::Debug for BioBdma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BioBdma").finish()
    }
}
#[doc = "BIO_BDMA"]
pub mod bio_bdma;
#[doc = "IOX"]
pub type Iox = crate::Periph<iox::RegisterBlock, 0x5012_f000>;
impl core::fmt::Debug for Iox {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iox").finish()
    }
}
#[doc = "IOX"]
pub mod iox;
#[doc = "PWM"]
pub type Pwm = crate::Periph<pwm::RegisterBlock, 0x5012_0000>;
impl core::fmt::Debug for Pwm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm").finish()
    }
}
#[doc = "PWM"]
pub mod pwm;
#[doc = "SDDC"]
pub type Sddc = crate::Periph<sddc::RegisterBlock, 0x5012_1000>;
impl core::fmt::Debug for Sddc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sddc").finish()
    }
}
#[doc = "SDDC"]
pub mod sddc;
#[doc = "CORESUB_SRAMTRM"]
pub type CoresubSramtrm = crate::Periph<coresub_sramtrm::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for CoresubSramtrm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CoresubSramtrm").finish()
    }
}
#[doc = "CORESUB_SRAMTRM"]
pub mod coresub_sramtrm;
#[doc = "MDMA"]
pub type Mdma = crate::Periph<mdma::RegisterBlock, 0x4001_2000>;
impl core::fmt::Debug for Mdma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mdma").finish()
    }
}
#[doc = "MDMA"]
pub mod mdma;
#[doc = "QFC"]
pub type Qfc = crate::Periph<qfc::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Qfc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qfc").finish()
    }
}
#[doc = "QFC"]
pub mod qfc;
#[doc = "MBOX_APB"]
pub type MboxApb = crate::Periph<mbox_apb::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for MboxApb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MboxApb").finish()
    }
}
#[doc = "MBOX_APB"]
pub mod mbox_apb;
#[doc = "RRC"]
pub type Rrc = crate::Periph<rrc::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Rrc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rrc").finish()
    }
}
#[doc = "RRC"]
pub mod rrc;
#[doc = "GLUECHAIN"]
pub type Gluechain = crate::Periph<gluechain::RegisterBlock, 0x4005_4000>;
impl core::fmt::Debug for Gluechain {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gluechain").finish()
    }
}
#[doc = "GLUECHAIN"]
pub mod gluechain;
#[doc = "MESH"]
pub type Mesh = crate::Periph<mesh::RegisterBlock, 0x4005_2000>;
impl core::fmt::Debug for Mesh {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mesh").finish()
    }
}
#[doc = "MESH"]
pub mod mesh;
#[doc = "SENSORC"]
pub type Sensorc = crate::Periph<sensorc::RegisterBlock, 0x4005_3000>;
impl core::fmt::Debug for Sensorc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sensorc").finish()
    }
}
#[doc = "SENSORC"]
pub mod sensorc;
#[doc = "AOBUREG"]
pub type Aobureg = crate::Periph<aobureg::RegisterBlock, 0x4006_5000>;
impl core::fmt::Debug for Aobureg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aobureg").finish()
    }
}
#[doc = "AOBUREG"]
pub mod aobureg;
#[doc = "AO_SYSCTRL"]
pub type AoSysctrl = crate::Periph<ao_sysctrl::RegisterBlock, 0x4006_0000>;
impl core::fmt::Debug for AoSysctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AoSysctrl").finish()
    }
}
#[doc = "AO_SYSCTRL"]
pub mod ao_sysctrl;
#[doc = "DKPC"]
pub type Dkpc = crate::Periph<dkpc::RegisterBlock, 0x4006_4000>;
impl core::fmt::Debug for Dkpc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dkpc").finish()
    }
}
#[doc = "DKPC"]
pub mod dkpc;
#[doc = "UDMA_CTRL"]
pub type UdmaCtrl = crate::Periph<udma_ctrl::RegisterBlock, 0x5010_0000>;
impl core::fmt::Debug for UdmaCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaCtrl").finish()
    }
}
#[doc = "UDMA_CTRL"]
pub mod udma_ctrl;
#[doc = "UDMA_UART_0"]
pub type UdmaUart0 = crate::Periph<udma_uart_0::RegisterBlock, 0x5010_1000>;
impl core::fmt::Debug for UdmaUart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaUart0").finish()
    }
}
#[doc = "UDMA_UART_0"]
pub mod udma_uart_0;
#[doc = "UDMA_UART_1"]
pub type UdmaUart1 = crate::Periph<udma_uart_0::RegisterBlock, 0x5010_2000>;
impl core::fmt::Debug for UdmaUart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaUart1").finish()
    }
}
#[doc = "UDMA_UART_1"]
pub use self::udma_uart_0 as udma_uart_1;
#[doc = "UDMA_UART_2"]
pub type UdmaUart2 = crate::Periph<udma_uart_0::RegisterBlock, 0x5010_3000>;
impl core::fmt::Debug for UdmaUart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaUart2").finish()
    }
}
#[doc = "UDMA_UART_2"]
pub use self::udma_uart_0 as udma_uart_2;
#[doc = "UDMA_UART_3"]
pub type UdmaUart3 = crate::Periph<udma_uart_0::RegisterBlock, 0x5010_4000>;
impl core::fmt::Debug for UdmaUart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaUart3").finish()
    }
}
#[doc = "UDMA_UART_3"]
pub use self::udma_uart_0 as udma_uart_3;
#[doc = "UDMA_SPIM_0"]
pub type UdmaSpim0 = crate::Periph<udma_spim_0::RegisterBlock, 0x5010_5000>;
impl core::fmt::Debug for UdmaSpim0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaSpim0").finish()
    }
}
#[doc = "UDMA_SPIM_0"]
pub mod udma_spim_0;
#[doc = "UDMA_SPIM_1"]
pub type UdmaSpim1 = crate::Periph<udma_spim_0::RegisterBlock, 0x5010_6000>;
impl core::fmt::Debug for UdmaSpim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaSpim1").finish()
    }
}
#[doc = "UDMA_SPIM_1"]
pub use self::udma_spim_0 as udma_spim_1;
#[doc = "UDMA_SPIM_2"]
pub type UdmaSpim2 = crate::Periph<udma_spim_0::RegisterBlock, 0x5010_7000>;
impl core::fmt::Debug for UdmaSpim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaSpim2").finish()
    }
}
#[doc = "UDMA_SPIM_2"]
pub use self::udma_spim_0 as udma_spim_2;
#[doc = "UDMA_SPIM_3"]
pub type UdmaSpim3 = crate::Periph<udma_spim_0::RegisterBlock, 0x5010_8000>;
impl core::fmt::Debug for UdmaSpim3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaSpim3").finish()
    }
}
#[doc = "UDMA_SPIM_3"]
pub use self::udma_spim_0 as udma_spim_3;
#[doc = "UDMA_I2C_0"]
pub type UdmaI2c0 = crate::Periph<udma_i2c_0::RegisterBlock, 0x5010_9000>;
impl core::fmt::Debug for UdmaI2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaI2c0").finish()
    }
}
#[doc = "UDMA_I2C_0"]
pub mod udma_i2c_0;
#[doc = "UDMA_I2C_1"]
pub type UdmaI2c1 = crate::Periph<udma_i2c_0::RegisterBlock, 0x5010_a000>;
impl core::fmt::Debug for UdmaI2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaI2c1").finish()
    }
}
#[doc = "UDMA_I2C_1"]
pub use self::udma_i2c_0 as udma_i2c_1;
#[doc = "UDMA_I2C_2"]
pub type UdmaI2c2 = crate::Periph<udma_i2c_0::RegisterBlock, 0x5010_b000>;
impl core::fmt::Debug for UdmaI2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaI2c2").finish()
    }
}
#[doc = "UDMA_I2C_2"]
pub use self::udma_i2c_0 as udma_i2c_2;
#[doc = "UDMA_I2C_3"]
pub type UdmaI2c3 = crate::Periph<udma_i2c_0::RegisterBlock, 0x5010_c000>;
impl core::fmt::Debug for UdmaI2c3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaI2c3").finish()
    }
}
#[doc = "UDMA_I2C_3"]
pub use self::udma_i2c_0 as udma_i2c_3;
#[doc = "UDMA_SDIO"]
pub type UdmaSdio = crate::Periph<udma_sdio::RegisterBlock, 0x5010_d000>;
impl core::fmt::Debug for UdmaSdio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaSdio").finish()
    }
}
#[doc = "UDMA_SDIO"]
pub mod udma_sdio;
#[doc = "UDMA_I2S"]
pub type UdmaI2s = crate::Periph<udma_i2s::RegisterBlock, 0x5010_e000>;
impl core::fmt::Debug for UdmaI2s {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaI2s").finish()
    }
}
#[doc = "UDMA_I2S"]
pub mod udma_i2s;
#[doc = "UDMA_CAMERA"]
pub type UdmaCamera = crate::Periph<udma_camera::RegisterBlock, 0x5010_f000>;
impl core::fmt::Debug for UdmaCamera {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaCamera").finish()
    }
}
#[doc = "UDMA_CAMERA"]
pub mod udma_camera;
#[doc = "UDMA_FILTER"]
pub type UdmaFilter = crate::Periph<udma_filter::RegisterBlock, 0x5011_0000>;
impl core::fmt::Debug for UdmaFilter {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaFilter").finish()
    }
}
#[doc = "UDMA_FILTER"]
pub mod udma_filter;
#[doc = "UDMA_SCIF"]
pub type UdmaScif = crate::Periph<udma_scif::RegisterBlock, 0x5011_1000>;
impl core::fmt::Debug for UdmaScif {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaScif").finish()
    }
}
#[doc = "UDMA_SCIF"]
pub mod udma_scif;
#[doc = "UDMA_SPIS_0"]
pub type UdmaSpis0 = crate::Periph<udma_spis_0::RegisterBlock, 0x5011_2000>;
impl core::fmt::Debug for UdmaSpis0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaSpis0").finish()
    }
}
#[doc = "UDMA_SPIS_0"]
pub mod udma_spis_0;
#[doc = "UDMA_SPIS_1"]
pub type UdmaSpis1 = crate::Periph<udma_spis_0::RegisterBlock, 0x5011_3000>;
impl core::fmt::Debug for UdmaSpis1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaSpis1").finish()
    }
}
#[doc = "UDMA_SPIS_1"]
pub use self::udma_spis_0 as udma_spis_1;
#[doc = "UDMA_ADC"]
pub type UdmaAdc = crate::Periph<udma_adc::RegisterBlock, 0x5011_4000>;
impl core::fmt::Debug for UdmaAdc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UdmaAdc").finish()
    }
}
#[doc = "UDMA_ADC"]
pub mod udma_adc;
#[doc = "BIO_FIFO0"]
pub type BioFifo0 = crate::Periph<bio_fifo0::RegisterBlock, 0x5012_9000>;
impl core::fmt::Debug for BioFifo0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BioFifo0").finish()
    }
}
#[doc = "BIO_FIFO0"]
pub mod bio_fifo0;
#[doc = "BIO_FIFO1"]
pub type BioFifo1 = crate::Periph<bio_fifo0::RegisterBlock, 0x5012_a000>;
impl core::fmt::Debug for BioFifo1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BioFifo1").finish()
    }
}
#[doc = "BIO_FIFO1"]
pub use self::bio_fifo0 as bio_fifo1;
#[doc = "BIO_FIFO2"]
pub type BioFifo2 = crate::Periph<bio_fifo0::RegisterBlock, 0x5012_b000>;
impl core::fmt::Debug for BioFifo2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BioFifo2").finish()
    }
}
#[doc = "BIO_FIFO2"]
pub use self::bio_fifo0 as bio_fifo2;
#[doc = "BIO_FIFO3"]
pub type BioFifo3 = crate::Periph<bio_fifo0::RegisterBlock, 0x5012_c000>;
impl core::fmt::Debug for BioFifo3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BioFifo3").finish()
    }
}
#[doc = "BIO_FIFO3"]
pub use self::bio_fifo0 as bio_fifo3;
#[doc = "D11CTIME"]
pub type D11ctime = crate::Periph<d11ctime::RegisterBlock, 0xe000_0000>;
impl core::fmt::Debug for D11ctime {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("D11ctime").finish()
    }
}
#[doc = "D11CTIME"]
pub mod d11ctime;
#[doc = "SUSRES"]
pub type Susres = crate::Periph<susres::RegisterBlock, 0xe000_1000>;
impl core::fmt::Debug for Susres {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Susres").finish()
    }
}
#[doc = "SUSRES"]
pub mod susres;
#[doc = "COREUSER"]
pub type Coreuser = crate::Periph<coreuser::RegisterBlock, 0xe000_2000>;
impl core::fmt::Debug for Coreuser {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Coreuser").finish()
    }
}
#[doc = "COREUSER"]
pub mod coreuser;
#[doc = "CSRTEST"]
pub type Csrtest = crate::Periph<csrtest::RegisterBlock, 0xe000_3000>;
impl core::fmt::Debug for Csrtest {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Csrtest").finish()
    }
}
#[doc = "CSRTEST"]
pub mod csrtest;
#[doc = "IRQARRAY0"]
pub type Irqarray0 = crate::Periph<irqarray0::RegisterBlock, 0xe000_4000>;
impl core::fmt::Debug for Irqarray0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray0").finish()
    }
}
#[doc = "IRQARRAY0"]
pub mod irqarray0;
#[doc = "IRQARRAY1"]
pub type Irqarray1 = crate::Periph<irqarray1::RegisterBlock, 0xe000_5000>;
impl core::fmt::Debug for Irqarray1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray1").finish()
    }
}
#[doc = "IRQARRAY1"]
pub mod irqarray1;
#[doc = "IRQARRAY2"]
pub type Irqarray2 = crate::Periph<irqarray2::RegisterBlock, 0xe001_0000>;
impl core::fmt::Debug for Irqarray2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray2").finish()
    }
}
#[doc = "IRQARRAY2"]
pub mod irqarray2;
#[doc = "IRQARRAY3"]
pub type Irqarray3 = crate::Periph<irqarray3::RegisterBlock, 0xe001_1000>;
impl core::fmt::Debug for Irqarray3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray3").finish()
    }
}
#[doc = "IRQARRAY3"]
pub mod irqarray3;
#[doc = "IRQARRAY4"]
pub type Irqarray4 = crate::Periph<irqarray4::RegisterBlock, 0xe001_2000>;
impl core::fmt::Debug for Irqarray4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray4").finish()
    }
}
#[doc = "IRQARRAY4"]
pub mod irqarray4;
#[doc = "IRQARRAY5"]
pub type Irqarray5 = crate::Periph<irqarray5::RegisterBlock, 0xe001_3000>;
impl core::fmt::Debug for Irqarray5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray5").finish()
    }
}
#[doc = "IRQARRAY5"]
pub mod irqarray5;
#[doc = "IRQARRAY6"]
pub type Irqarray6 = crate::Periph<irqarray6::RegisterBlock, 0xe001_4000>;
impl core::fmt::Debug for Irqarray6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray6").finish()
    }
}
#[doc = "IRQARRAY6"]
pub mod irqarray6;
#[doc = "IRQARRAY7"]
pub type Irqarray7 = crate::Periph<irqarray7::RegisterBlock, 0xe001_5000>;
impl core::fmt::Debug for Irqarray7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray7").finish()
    }
}
#[doc = "IRQARRAY7"]
pub mod irqarray7;
#[doc = "IRQARRAY8"]
pub type Irqarray8 = crate::Periph<irqarray8::RegisterBlock, 0xe001_6000>;
impl core::fmt::Debug for Irqarray8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray8").finish()
    }
}
#[doc = "IRQARRAY8"]
pub mod irqarray8;
#[doc = "IRQARRAY9"]
pub type Irqarray9 = crate::Periph<irqarray9::RegisterBlock, 0xe001_7000>;
impl core::fmt::Debug for Irqarray9 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray9").finish()
    }
}
#[doc = "IRQARRAY9"]
pub mod irqarray9;
#[doc = "IRQARRAY10"]
pub type Irqarray10 = crate::Periph<irqarray10::RegisterBlock, 0xe000_6000>;
impl core::fmt::Debug for Irqarray10 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray10").finish()
    }
}
#[doc = "IRQARRAY10"]
pub mod irqarray10;
#[doc = "IRQARRAY11"]
pub type Irqarray11 = crate::Periph<irqarray11::RegisterBlock, 0xe000_7000>;
impl core::fmt::Debug for Irqarray11 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray11").finish()
    }
}
#[doc = "IRQARRAY11"]
pub mod irqarray11;
#[doc = "IRQARRAY12"]
pub type Irqarray12 = crate::Periph<irqarray12::RegisterBlock, 0xe000_8000>;
impl core::fmt::Debug for Irqarray12 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray12").finish()
    }
}
#[doc = "IRQARRAY12"]
pub mod irqarray12;
#[doc = "IRQARRAY13"]
pub type Irqarray13 = crate::Periph<irqarray13::RegisterBlock, 0xe000_9000>;
impl core::fmt::Debug for Irqarray13 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray13").finish()
    }
}
#[doc = "IRQARRAY13"]
pub mod irqarray13;
#[doc = "IRQARRAY14"]
pub type Irqarray14 = crate::Periph<irqarray14::RegisterBlock, 0xe000_a000>;
impl core::fmt::Debug for Irqarray14 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray14").finish()
    }
}
#[doc = "IRQARRAY14"]
pub mod irqarray14;
#[doc = "IRQARRAY15"]
pub type Irqarray15 = crate::Periph<irqarray15::RegisterBlock, 0xe000_b000>;
impl core::fmt::Debug for Irqarray15 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray15").finish()
    }
}
#[doc = "IRQARRAY15"]
pub mod irqarray15;
#[doc = "IRQARRAY16"]
pub type Irqarray16 = crate::Periph<irqarray16::RegisterBlock, 0xe000_c000>;
impl core::fmt::Debug for Irqarray16 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray16").finish()
    }
}
#[doc = "IRQARRAY16"]
pub mod irqarray16;
#[doc = "IRQARRAY17"]
pub type Irqarray17 = crate::Periph<irqarray17::RegisterBlock, 0xe000_d000>;
impl core::fmt::Debug for Irqarray17 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray17").finish()
    }
}
#[doc = "IRQARRAY17"]
pub mod irqarray17;
#[doc = "IRQARRAY18"]
pub type Irqarray18 = crate::Periph<irqarray18::RegisterBlock, 0xe000_e000>;
impl core::fmt::Debug for Irqarray18 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray18").finish()
    }
}
#[doc = "IRQARRAY18"]
pub mod irqarray18;
#[doc = "IRQARRAY19"]
pub type Irqarray19 = crate::Periph<irqarray19::RegisterBlock, 0xe000_f000>;
impl core::fmt::Debug for Irqarray19 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Irqarray19").finish()
    }
}
#[doc = "IRQARRAY19"]
pub mod irqarray19;
#[doc = "MAILBOX"]
pub type Mailbox = crate::Periph<mailbox::RegisterBlock, 0xe001_8000>;
impl core::fmt::Debug for Mailbox {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mailbox").finish()
    }
}
#[doc = "MAILBOX"]
pub mod mailbox;
#[doc = "MB_CLIENT"]
pub type MbClient = crate::Periph<mb_client::RegisterBlock, 0xe001_9000>;
impl core::fmt::Debug for MbClient {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MbClient").finish()
    }
}
#[doc = "MB_CLIENT"]
pub mod mb_client;
#[doc = "RESETVALUE"]
pub type Resetvalue = crate::Periph<resetvalue::RegisterBlock, 0xe001_a000>;
impl core::fmt::Debug for Resetvalue {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Resetvalue").finish()
    }
}
#[doc = "RESETVALUE"]
pub mod resetvalue;
#[doc = "TICKTIMER"]
pub type Ticktimer = crate::Periph<ticktimer::RegisterBlock, 0xe001_b000>;
impl core::fmt::Debug for Ticktimer {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ticktimer").finish()
    }
}
#[doc = "TICKTIMER"]
pub mod ticktimer;
#[doc = "TIMER0"]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0xe001_c000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "TIMER0"]
pub mod timer0;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "PL230"]
    pub pl230: Pl230,
    #[doc = "ALU"]
    pub alu: Alu,
    #[doc = "AES"]
    pub aes: Aes,
    #[doc = "COMBOHASH"]
    pub combohash: Combohash,
    #[doc = "PKE"]
    pub pke: Pke,
    #[doc = "TRNG"]
    pub trng: Trng,
    #[doc = "SCEDMA"]
    pub scedma: Scedma,
    #[doc = "SCE_GLBSFR"]
    pub sce_glbsfr: SceGlbsfr,
    #[doc = "DUART"]
    pub duart: Duart,
    #[doc = "RBIST_WRP"]
    pub rbist_wrp: RbistWrp,
    #[doc = "EVC"]
    pub evc: Evc,
    #[doc = "SYSCTRL"]
    pub sysctrl: Sysctrl,
    #[doc = "BIO_BDMA"]
    pub bio_bdma: BioBdma,
    #[doc = "IOX"]
    pub iox: Iox,
    #[doc = "PWM"]
    pub pwm: Pwm,
    #[doc = "SDDC"]
    pub sddc: Sddc,
    #[doc = "CORESUB_SRAMTRM"]
    pub coresub_sramtrm: CoresubSramtrm,
    #[doc = "MDMA"]
    pub mdma: Mdma,
    #[doc = "QFC"]
    pub qfc: Qfc,
    #[doc = "MBOX_APB"]
    pub mbox_apb: MboxApb,
    #[doc = "RRC"]
    pub rrc: Rrc,
    #[doc = "GLUECHAIN"]
    pub gluechain: Gluechain,
    #[doc = "MESH"]
    pub mesh: Mesh,
    #[doc = "SENSORC"]
    pub sensorc: Sensorc,
    #[doc = "AOBUREG"]
    pub aobureg: Aobureg,
    #[doc = "AO_SYSCTRL"]
    pub ao_sysctrl: AoSysctrl,
    #[doc = "DKPC"]
    pub dkpc: Dkpc,
    #[doc = "UDMA_CTRL"]
    pub udma_ctrl: UdmaCtrl,
    #[doc = "UDMA_UART_0"]
    pub udma_uart_0: UdmaUart0,
    #[doc = "UDMA_UART_1"]
    pub udma_uart_1: UdmaUart1,
    #[doc = "UDMA_UART_2"]
    pub udma_uart_2: UdmaUart2,
    #[doc = "UDMA_UART_3"]
    pub udma_uart_3: UdmaUart3,
    #[doc = "UDMA_SPIM_0"]
    pub udma_spim_0: UdmaSpim0,
    #[doc = "UDMA_SPIM_1"]
    pub udma_spim_1: UdmaSpim1,
    #[doc = "UDMA_SPIM_2"]
    pub udma_spim_2: UdmaSpim2,
    #[doc = "UDMA_SPIM_3"]
    pub udma_spim_3: UdmaSpim3,
    #[doc = "UDMA_I2C_0"]
    pub udma_i2c_0: UdmaI2c0,
    #[doc = "UDMA_I2C_1"]
    pub udma_i2c_1: UdmaI2c1,
    #[doc = "UDMA_I2C_2"]
    pub udma_i2c_2: UdmaI2c2,
    #[doc = "UDMA_I2C_3"]
    pub udma_i2c_3: UdmaI2c3,
    #[doc = "UDMA_SDIO"]
    pub udma_sdio: UdmaSdio,
    #[doc = "UDMA_I2S"]
    pub udma_i2s: UdmaI2s,
    #[doc = "UDMA_CAMERA"]
    pub udma_camera: UdmaCamera,
    #[doc = "UDMA_FILTER"]
    pub udma_filter: UdmaFilter,
    #[doc = "UDMA_SCIF"]
    pub udma_scif: UdmaScif,
    #[doc = "UDMA_SPIS_0"]
    pub udma_spis_0: UdmaSpis0,
    #[doc = "UDMA_SPIS_1"]
    pub udma_spis_1: UdmaSpis1,
    #[doc = "UDMA_ADC"]
    pub udma_adc: UdmaAdc,
    #[doc = "BIO_FIFO0"]
    pub bio_fifo0: BioFifo0,
    #[doc = "BIO_FIFO1"]
    pub bio_fifo1: BioFifo1,
    #[doc = "BIO_FIFO2"]
    pub bio_fifo2: BioFifo2,
    #[doc = "BIO_FIFO3"]
    pub bio_fifo3: BioFifo3,
    #[doc = "D11CTIME"]
    pub d11ctime: D11ctime,
    #[doc = "SUSRES"]
    pub susres: Susres,
    #[doc = "COREUSER"]
    pub coreuser: Coreuser,
    #[doc = "CSRTEST"]
    pub csrtest: Csrtest,
    #[doc = "IRQARRAY0"]
    pub irqarray0: Irqarray0,
    #[doc = "IRQARRAY1"]
    pub irqarray1: Irqarray1,
    #[doc = "IRQARRAY2"]
    pub irqarray2: Irqarray2,
    #[doc = "IRQARRAY3"]
    pub irqarray3: Irqarray3,
    #[doc = "IRQARRAY4"]
    pub irqarray4: Irqarray4,
    #[doc = "IRQARRAY5"]
    pub irqarray5: Irqarray5,
    #[doc = "IRQARRAY6"]
    pub irqarray6: Irqarray6,
    #[doc = "IRQARRAY7"]
    pub irqarray7: Irqarray7,
    #[doc = "IRQARRAY8"]
    pub irqarray8: Irqarray8,
    #[doc = "IRQARRAY9"]
    pub irqarray9: Irqarray9,
    #[doc = "IRQARRAY10"]
    pub irqarray10: Irqarray10,
    #[doc = "IRQARRAY11"]
    pub irqarray11: Irqarray11,
    #[doc = "IRQARRAY12"]
    pub irqarray12: Irqarray12,
    #[doc = "IRQARRAY13"]
    pub irqarray13: Irqarray13,
    #[doc = "IRQARRAY14"]
    pub irqarray14: Irqarray14,
    #[doc = "IRQARRAY15"]
    pub irqarray15: Irqarray15,
    #[doc = "IRQARRAY16"]
    pub irqarray16: Irqarray16,
    #[doc = "IRQARRAY17"]
    pub irqarray17: Irqarray17,
    #[doc = "IRQARRAY18"]
    pub irqarray18: Irqarray18,
    #[doc = "IRQARRAY19"]
    pub irqarray19: Irqarray19,
    #[doc = "MAILBOX"]
    pub mailbox: Mailbox,
    #[doc = "MB_CLIENT"]
    pub mb_client: MbClient,
    #[doc = "RESETVALUE"]
    pub resetvalue: Resetvalue,
    #[doc = "TICKTIMER"]
    pub ticktimer: Ticktimer,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            pl230: Pl230::steal(),
            alu: Alu::steal(),
            aes: Aes::steal(),
            combohash: Combohash::steal(),
            pke: Pke::steal(),
            trng: Trng::steal(),
            scedma: Scedma::steal(),
            sce_glbsfr: SceGlbsfr::steal(),
            duart: Duart::steal(),
            rbist_wrp: RbistWrp::steal(),
            evc: Evc::steal(),
            sysctrl: Sysctrl::steal(),
            bio_bdma: BioBdma::steal(),
            iox: Iox::steal(),
            pwm: Pwm::steal(),
            sddc: Sddc::steal(),
            coresub_sramtrm: CoresubSramtrm::steal(),
            mdma: Mdma::steal(),
            qfc: Qfc::steal(),
            mbox_apb: MboxApb::steal(),
            rrc: Rrc::steal(),
            gluechain: Gluechain::steal(),
            mesh: Mesh::steal(),
            sensorc: Sensorc::steal(),
            aobureg: Aobureg::steal(),
            ao_sysctrl: AoSysctrl::steal(),
            dkpc: Dkpc::steal(),
            udma_ctrl: UdmaCtrl::steal(),
            udma_uart_0: UdmaUart0::steal(),
            udma_uart_1: UdmaUart1::steal(),
            udma_uart_2: UdmaUart2::steal(),
            udma_uart_3: UdmaUart3::steal(),
            udma_spim_0: UdmaSpim0::steal(),
            udma_spim_1: UdmaSpim1::steal(),
            udma_spim_2: UdmaSpim2::steal(),
            udma_spim_3: UdmaSpim3::steal(),
            udma_i2c_0: UdmaI2c0::steal(),
            udma_i2c_1: UdmaI2c1::steal(),
            udma_i2c_2: UdmaI2c2::steal(),
            udma_i2c_3: UdmaI2c3::steal(),
            udma_sdio: UdmaSdio::steal(),
            udma_i2s: UdmaI2s::steal(),
            udma_camera: UdmaCamera::steal(),
            udma_filter: UdmaFilter::steal(),
            udma_scif: UdmaScif::steal(),
            udma_spis_0: UdmaSpis0::steal(),
            udma_spis_1: UdmaSpis1::steal(),
            udma_adc: UdmaAdc::steal(),
            bio_fifo0: BioFifo0::steal(),
            bio_fifo1: BioFifo1::steal(),
            bio_fifo2: BioFifo2::steal(),
            bio_fifo3: BioFifo3::steal(),
            d11ctime: D11ctime::steal(),
            susres: Susres::steal(),
            coreuser: Coreuser::steal(),
            csrtest: Csrtest::steal(),
            irqarray0: Irqarray0::steal(),
            irqarray1: Irqarray1::steal(),
            irqarray2: Irqarray2::steal(),
            irqarray3: Irqarray3::steal(),
            irqarray4: Irqarray4::steal(),
            irqarray5: Irqarray5::steal(),
            irqarray6: Irqarray6::steal(),
            irqarray7: Irqarray7::steal(),
            irqarray8: Irqarray8::steal(),
            irqarray9: Irqarray9::steal(),
            irqarray10: Irqarray10::steal(),
            irqarray11: Irqarray11::steal(),
            irqarray12: Irqarray12::steal(),
            irqarray13: Irqarray13::steal(),
            irqarray14: Irqarray14::steal(),
            irqarray15: Irqarray15::steal(),
            irqarray16: Irqarray16::steal(),
            irqarray17: Irqarray17::steal(),
            irqarray18: Irqarray18::steal(),
            irqarray19: Irqarray19::steal(),
            mailbox: Mailbox::steal(),
            mb_client: MbClient::steal(),
            resetvalue: Resetvalue::steal(),
            ticktimer: Ticktimer::steal(),
            timer0: Timer0::steal(),
        }
    }
}
