use bao1x_pac::Iox;

use crate::gpio::pin::*;

pub mod pin;
mod port;

pub struct Pins {
    pub pa00: Pin<PA00, Input>,
    pub pa01: Pin<PA01, Input>,
    pub pa02: Pin<PA02, Input>,
    pub pa03: Pin<PA03, Input>,
    pub pa04: Pin<PA04, Input>,
    pub pa05: Pin<PA05, Input>,
    pub pa06: Pin<PA06, Input>,
    pub pa07: Pin<PA07, Input>,

    pub pb00: Pin<PB00, Input>,
    pub pb01: Pin<PB01, Input>,
    pub pb02: Pin<PB02, Input>,
    pub pb03: Pin<PB03, Input>,
    pub pb04: Pin<PB04, Input>,
    pub pb05: Pin<PB05, Input>,
    pub pb06: Pin<PB06, Input>,
    pub pb07: Pin<PB07, Input>,
    pub pb08: Pin<PB08, Input>,
    pub pb09: Pin<PB09, Input>,
    pub pb10: Pin<PB10, Input>,
    pub pb11: Pin<PB11, Input>,
    pub pb12: Pin<PB12, Input>,
    pub pb13: Pin<PB13, Input>,
    pub pb14: Pin<PB14, Input>,
    pub pb15: Pin<PB15, Input>,

    pub pc00: Pin<PC00, Input>,
    pub pc01: Pin<PC01, Input>,
    pub pc02: Pin<PC02, Input>,
    pub pc03: Pin<PC03, Input>,
    pub pc04: Pin<PC04, Input>,
    pub pc05: Pin<PC05, Input>,
    pub pc06: Pin<PC06, Input>,
    pub pc07: Pin<PC07, Input>,
    pub pc08: Pin<PC08, Input>,
    pub pc09: Pin<PC09, Input>,
    pub pc10: Pin<PC10, Input>,
    pub pc11: Pin<PC11, Input>,
    pub pc12: Pin<PC12, Input>,
    pub pc13: Pin<PC13, Input>,
    pub pc14: Pin<PC14, Input>,
    pub pc15: Pin<PC15, Input>,

    pub pd00: Pin<PD00, Input>,
    pub pd01: Pin<PD01, Input>,
    pub pd02: Pin<PD02, Input>,
    pub pd03: Pin<PD03, Input>,
    pub pd04: Pin<PD04, Input>,
    pub pd05: Pin<PD05, Input>,
    pub pd06: Pin<PD06, Input>,
    pub pd07: Pin<PD07, Input>,
    pub pd08: Pin<PD08, Input>,
    pub pd09: Pin<PD09, Input>,
    pub pd10: Pin<PD10, Input>,
    pub pd11: Pin<PD11, Input>,
    pub pd12: Pin<PD12, Input>,
    pub pd13: Pin<PD13, Input>,
    pub pd14: Pin<PD14, Input>,
    pub pd15: Pin<PD15, Input>,

    pub pe00: Pin<PE00, Input>,
    pub pe01: Pin<PE01, Input>,
    pub pe02: Pin<PE02, Input>,
    pub pe03: Pin<PE03, Input>,
    pub pe04: Pin<PE04, Input>,
    pub pe05: Pin<PE05, Input>,
    pub pe06: Pin<PE06, Input>,
    pub pe07: Pin<PE07, Input>,
    pub pe08: Pin<PE08, Input>,
    pub pe09: Pin<PE09, Input>,
    pub pe10: Pin<PE10, Input>,
    pub pe11: Pin<PE11, Input>,
    pub pe12: Pin<PE12, Input>,
    pub pe13: Pin<PE13, Input>,
    pub pe14: Pin<PE14, Input>,
    pub pe15: Pin<PE15, Input>,
}

impl Pins {
    pub fn new(_regs: Iox) -> Self {
        Self {
            pa00: Pin::new(),
            pa01: Pin::new(),
            pa02: Pin::new(),
            pa03: Pin::new(),
            pa04: Pin::new(),
            pa05: Pin::new(),
            pa06: Pin::new(),
            pa07: Pin::new(),

            pb00: Pin::new(),
            pb01: Pin::new(),
            pb02: Pin::new(),
            pb03: Pin::new(),
            pb04: Pin::new(),
            pb05: Pin::new(),
            pb06: Pin::new(),
            pb07: Pin::new(),
            pb08: Pin::new(),
            pb09: Pin::new(),
            pb10: Pin::new(),
            pb11: Pin::new(),
            pb12: Pin::new(),
            pb13: Pin::new(),
            pb14: Pin::new(),
            pb15: Pin::new(),

            pc00: Pin::new(),
            pc01: Pin::new(),
            pc02: Pin::new(),
            pc03: Pin::new(),
            pc04: Pin::new(),
            pc05: Pin::new(),
            pc06: Pin::new(),
            pc07: Pin::new(),
            pc08: Pin::new(),
            pc09: Pin::new(),
            pc10: Pin::new(),
            pc11: Pin::new(),
            pc12: Pin::new(),
            pc13: Pin::new(),
            pc14: Pin::new(),
            pc15: Pin::new(),

            pd00: Pin::new(),
            pd01: Pin::new(),
            pd02: Pin::new(),
            pd03: Pin::new(),
            pd04: Pin::new(),
            pd05: Pin::new(),
            pd06: Pin::new(),
            pd07: Pin::new(),
            pd08: Pin::new(),
            pd09: Pin::new(),
            pd10: Pin::new(),
            pd11: Pin::new(),
            pd12: Pin::new(),
            pd13: Pin::new(),
            pd14: Pin::new(),
            pd15: Pin::new(),

            pe00: Pin::new(),
            pe01: Pin::new(),
            pe02: Pin::new(),
            pe03: Pin::new(),
            pe04: Pin::new(),
            pe05: Pin::new(),
            pe06: Pin::new(),
            pe07: Pin::new(),
            pe08: Pin::new(),
            pe09: Pin::new(),
            pe10: Pin::new(),
            pe11: Pin::new(),
            pe12: Pin::new(),
            pe13: Pin::new(),
            pe14: Pin::new(),
            pe15: Pin::new(),
        }
    }
}
